[package]
name = "gabes_graphics"
version = "0.1.0"
edition = "2021"

[[example]]
name = "projectile"
path = "examples/projectile.rs"

[[example]]
name = "clock"
path = "examples/clock.rs"

[dependencies]
nalgebra = "0.33.0"
approx = "0.5.1"
